# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
